name: Comment on PR with ClickUp task link

on:
  pull_request:
    types: [opened]

jobs:
  add-comment:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Extract branch name
        id: extract
        run: echo "branch=${{ github.head_ref }}" >> $GITHUB_ENV

      - name: Check branch name and comment
        id: check-and-comment
        run: |
          BRANCH_NAME="${{ env.branch }}"
          if [[ "$BRANCH_NAME" =~ .*#([a-zA-Z0-9]+).* ]]; then
            TASK_ID=${BASH_REMATCH[1]}
            COMMENT="This PR is linked to ClickUp task: https://app.clickup.com/t/${TASK_ID}"
            echo "comment=$COMMENT" >> $GITHUB_ENV
          else
            echo "Branch name does not match the required pattern."
            echo "comment=" >> $GITHUB_ENV
          fi
        shell: bash

      - name: Add comment to PR
        if: env.comment
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        run: |
          gh pr comment ${{ github.event.pull_request.number }} --body "${{ env.comment }}"
        shell: bash
